version: '3'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    container_name: es01
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - /data/share/elasticsearch/data/hobbitdata.informatik.uni-leipzig.de/homes/wikipediaElasticSearchdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  factcheckservice:
    image: dicegroup/factcheck-service:1.0.5
    ports:
      - 8888:8080
